binary-ghc-args:
- -O1
- -threaded
- -fenable-rewrite-rules
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Git: https://github.com/gelisam/category-syntax 3074f23f8597569fad4b1c4480b8a5efd6d098b2

  Hackage: multiplate 0.0.3


'
ghc-args:
- -fenable-rewrite-rules
- -fno-max-relevant-binds
excluded-modules:
- Arrow.hs
- Auto.hs
- Control/Arrow/CCA/Optimize.hs
- Control/Arrow/TH.hs
- src/Control/Arrow/CCA/AExp.hs
- src/Control/Arrow/CCA/NoQ.hs
- src/Control/CCA/Normalize.hs
- src/Control/Category/Monoidal.hs
- src/Data/Compos.hs
- src/Morte/Core.hs
