binary-ghc-args:
- -O2
- -threaded
- -fenable-rewrite-rules
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: th-alpha 0.2.0.2

  Git: https://github.com/gelisam/category-syntax 3074f23f8597569fad4b1c4480b8a5efd6d098b2

'
ghc-args:
- -fenable-rewrite-rules
excluded-modules:
- Arrow.hs
- Auto.hs
- Control/Arrow/CCA/Optimize.hs
- src/Control/Category/Monoidal.hs
- src/Morte/Core.hs
